# Generated by Django 6.1.1 on 2026-09-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
