# Generated by Django 6.1.1 on 2026-09-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_libro_portada_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='obra_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
